// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stefanini.bob.management.domain;

import com.stefanini.bob.management.domain.WorkGroup;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect WorkGroup_Roo_Configurable {
    
    declare @type: WorkGroup: @Configurable;
    
}
