// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.stefanini.bob.management.domain;

import com.stefanini.bob.management.domain.WorkGroup;

privileged aspect WorkGroup_Roo_JavaBean {
    
    public String WorkGroup.getName() {
        return this.name;
    }
    
    public void WorkGroup.setName(String name) {
        this.name = name;
    }
    
}
